// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQsLZE-KJaXJhYR3eamLnTI3dAYTWotjo',
    appId: '1:51101515805:web:f51c1a88573197ca5a06f4',
    messagingSenderId: '51101515805',
    projectId: 'egtema3-el3am',
    authDomain: 'egtema3-el3am.firebaseapp.com',
    storageBucket: 'egtema3-el3am.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeeoZynUUvsqNirsTlxuZNX461LWw9fA',
    appId: '1:51101515805:android:65fb6e8683f145c05a06f4',
    messagingSenderId: '51101515805',
    projectId: 'egtema3-el3am',
    storageBucket: 'egtema3-el3am.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSwmJq1Gape3FBzwQx3BUpoF2SCLLTEZ8',
    appId: '1:51101515805:ios:d78ca3cff84ed7115a06f4',
    messagingSenderId: '51101515805',
    projectId: 'egtema3-el3am',
    storageBucket: 'egtema3-el3am.firebasestorage.app',
    iosBundleId: 'com.example.egtema3elegtema3el3am',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSwmJq1Gape3FBzwQx3BUpoF2SCLLTEZ8',
    appId: '1:51101515805:ios:d78ca3cff84ed7115a06f4',
    messagingSenderId: '51101515805',
    projectId: 'egtema3-el3am',
    storageBucket: 'egtema3-el3am.firebasestorage.app',
    iosBundleId: 'com.example.egtema3elegtema3el3am',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQsLZE-KJaXJhYR3eamLnTI3dAYTWotjo',
    appId: '1:51101515805:web:3aa2959b51eb0cd95a06f4',
    messagingSenderId: '51101515805',
    projectId: 'egtema3-el3am',
    authDomain: 'egtema3-el3am.firebaseapp.com',
    storageBucket: 'egtema3-el3am.firebasestorage.app',
  );
}
